rental_django/rental_django/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('property.urls', namespace='property')),
    path('', include('users.urls', namespace='users'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rental_django/users/urls.py
from django.urls import path
from .views import index_view, login_view, register_view, logout_view, dashboard_view, edit_profile_view

app_name = 'users'

urlpatterns = [
    path('', index_view, name='index'),
    path('entrar/', login_view, name='login'),
    path('registro/', register_view, name='register'),
    path('salir/', logout_view, name='logout'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('dashboard/editar/', edit_profile_view, name='edit_profile')
]

rental_django/templates/dashboard.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="dashboard section">
    <!-- Container Start -->
    <div class="container">
      <!-- Row Start -->
      <div class="row">
        <div class="col-lg-4">
          <div class="sidebar">
            <!-- User Widget -->
            <div class="widget user-dashboard-profile">
              <!-- User Name -->
              <h5 class="text-center">{{ request.user.get_full_name }}</h5>
              <p class="text-center font-weight-bold">{{ extra_user_data.rut }}</p>
              <p class="text-center"><span class="font-weight-bold">Dirección:</span> {{ extra_user_data.address }}</p>
              <p class="text-center"><span class="font-weight-bold">Telefono:</span> {{ extra_user_data.phone }}</p>
              <p>Registrado desde el {{ request.user.date_joined|date:"j \d\e F  Y" }}</p>
              <a href="{% url 'users:edit_profile' %}" class="btn btn-main-sm">Editar perfil</a>
            </div>
            <!-- Dashboard Links -->
            <div class="widget user-dashboard-menu">
              <ul>
                <li class="active"><a href="dashboard-my-ads.html"><i class="fa fa-user"></i> Mis publicaciones</a></li>
                <li><a href="dashboard-favourite-ads.html"><i class="fa fa-bookmark-o"></i> Favourite Ads
                    <span>5</span></a></li>
                <li><a href="dashboard-archived-ads.html"><i class="fa fa-file-archive-o"></i>Archived Ads
                    <span>12</span></a></li>
                <li><a href="dashboard-pending-ads.html"><i class="fa fa-bolt"></i> Pending Approval<span>23</span></a>
                </li>
                <li><a href="{% url 'users:logout' %}"><i class="fa fa-cog"></i> Salir</a></li>
              </ul>
            </div>
            
          </div>
        </div>
        <div class="col-lg-8">
          <!-- Recently Favorited -->
          <div class="widget dashboard-container my-adslist">
            <h3 class="widget-header">Mis Publicaciones</h3>
            <table class="table table-responsive product-dashboard-table">
              <thead>
                <tr>
                  <th>Image</th>
                  <th>Product Title</th>
                  <th class="text-center">Category</th>
                  <th class="text-center">Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="product-thumb">
                    <img width="80px" height="auto" src="images/products/products-1.jpg" alt="image description"></td>
                  <td class="product-details">
                    <h3 class="title">Macbook Pro 15inch</h3>
                    <span class="add-id"><strong>Ad ID:</strong> ng3D5hAMHPajQrM</span>
                    <span><strong>Posted on: </strong><time>Jun 27, 2017</time> </span>
                    <span class="status active"><strong>Status</strong>Active</span>
                    <span class="location"><strong>Location</strong>Dhaka,Bangladesh</span>
                  </td>
                  <td class="product-category"><span class="categories">Laptops</span></td>
                  <td class="action" data-title="Action">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a data-toggle="tooltip" data-placement="top" title="view" class="view" href="category.html">
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" href="dashboard.html">
                            <i class="fa fa-pencil"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" href="dashboard.html">
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                <tr>
  
                  <td class="product-thumb">
                    <img width="80px" height="auto" src="images/products/products-2.jpg" alt="image description"></td>
                  <td class="product-details">
                    <h3 class="title">Study Table Combo</h3>
                    <span class="add-id"><strong>Ad ID:</strong> ng3D5hAMHPajQrM</span>
                    <span><strong>Posted on: </strong><time>Feb 12, 2017</time> </span>
                    <span class="status active"><strong>Status</strong>Active</span>
                    <span class="location"><strong>Location</strong>USA</span>
                  </td>
                  <td class="product-category"><span class="categories">Laptops</span></td>
                  <td class="action" data-title="Action">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a data-toggle="tooltip" data-placement="top" title="View" class="view" href="category.html">
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" href="dashboard.html">
                            <i class="fa fa-pencil"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" href="dashboard.html">
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td class="product-thumb">
                    <img width="80px" height="auto" src="images/products/products-3.jpg" alt="image description"></td>
                  <td class="product-details">
                    <h3 class="title">Macbook Pro 15inch</h3>
                    <span class="add-id"><strong>Ad ID:</strong> ng3D5hAMHPajQrM</span>
                    <span><strong>Posted on: </strong><time>Jun 27, 2017</time> </span>
                    <span class="status active"><strong>Status</strong>Active</span>
                    <span class="location"><strong>Location</strong>Dhaka,Bangladesh</span>
                  </td>
                  <td class="product-category"><span class="categories">Laptops</span></td>
                  <td class="action" data-title="Action">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a data-toggle="tooltip" data-placement="top" title="View" class="view" href="category.html">
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" href="dashboard.html">
                            <i class="fa fa-pencil"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" href="dashboard.html">
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                <tr>
  
                  <td class="product-thumb">
                    <img width="80px" height="auto" src="images/products/products-4.jpg" alt="image description"></td>
                  <td class="product-details">
                    <h3 class="title">Macbook Pro 15inch</h3>
                    <span class="add-id"><strong>Ad ID:</strong> ng3D5hAMHPajQrM</span>
                    <span><strong>Posted on: </strong><time>Jun 27, 2017</time> </span>
                    <span class="status active"><strong>Status</strong>Active</span>
                    <span class="location"><strong>Location</strong>Dhaka,Bangladesh</span>
                  </td>
                  <td class="product-category"><span class="categories">Laptops</span></td>
                  <td class="action" data-title="Action">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a data-toggle="tooltip" data-placement="top" title="View" class="view" href="category.html">
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" href="dashboard.html">
                            <i class="fa fa-pencil"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" href="dashboard.html">
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
                <tr>
  
                  <td class="product-thumb">
                    <img width="80px" height="auto" src="images/products/products-1.jpg" alt="image description"></td>
                  <td class="product-details">
                    <h3 class="title">Macbook Pro 15inch</h3>
                    <span class="add-id"><strong>Ad ID:</strong> ng3D5hAMHPajQrM</span>
                    <span><strong>Posted on: </strong><time>Jun 27, 2017</time> </span>
                    <span class="status active"><strong>Status</strong>Active</span>
                    <span class="location"><strong>Location</strong>Dhaka,Bangladesh</span>
                  </td>
                  <td class="product-category"><span class="categories">Laptops</span></td>
                  <td class="action" data-title="Action">
                    <div class="">
                      <ul class="list-inline justify-content-center">
                        <li class="list-inline-item">
                          <a href="category.html" data-toggle="tooltip" data-placement="top" title="View" class="view">
                            <i class="fa fa-eye"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" href="dashboard.html">
                            <i class="fa fa-pencil"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" href="dashboard.html">
                            <i class="fa fa-trash"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
  
          </div>
  
          <!-- Deberia haber paginacion para despues
          <div class="pagination justify-content-center">
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                <li class="page-item">
                  <a class="page-link" href="dashboard.html" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item"><a class="page-link" href="dashboard.html">1</a></li>
                <li class="page-item active"><a class="page-link" href="dashboard.html">2</a></li>
                <li class="page-item"><a class="page-link" href="dashboard.html">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="dashboard.html" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          paginacion -->
  
        </div>
      </div>
      <!-- Row End -->
    </div>
    <!-- Container End -->
  </section>
  {% endblock %}

rental_django/templates/login.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="login py-5 border-top-1">
	<div class="container">
	  <div class="row justify-content-center">
		<div class="col-lg-5 col-md-8 align-item-center">
		  <div class="border">
			<h3 class="bg-gray p-4">Iniciar Sesión</h3>
			<form method="post">
				{% csrf_token %}
			  <fieldset class="p-4">
				{{ form.username | add_class:"form-control mb-3" | attr:"placeholder:Correo o Usuario" | attr:"required" }}
				{{ form.username.errors}}
				{{ form.password | add_class:"form-control mb-3" | attr:"placeholder:Contraseña" | attr:"required" }}
				{{ form.password.errors}}
				<button type="submit" class="btn btn-primary font-weight-bold mt-3">Entrar</button>
				<a class="mt-3 d-inline-block text-primary" href="register.html">Registrarse</a>
			  </fieldset>
			</form>
		  </div>
		</div>
	  </div>
	</div>
  </section>
    
{% endblock %}

rental_django/templates/profile.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="user-profile section">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user">
						<h5 class="text-center">{{ request.user.get_full_name }}</h5>
						<p class="text-center">{{ request.user.username }}</p>
					</div>
					<!-- Dashboard Links -->
          <div class="widget user-dashboard-menu">
            <ul>
              <li><a href="index.html">Savings Dashboard</a></li>
              <li><a href="index.html">Saved Offer <span>(5)</span></a></li>
              <li><a href="index.html">Favourite Stores <span>(3)</span></a></li>
              <li><a href="index.html">Recommended</a></li>
            </ul>
          </div>
				</div>
			</div>
			<div class="col-lg-8">
				<!-- Edit Profile Welcome Text -->
				<div class="widget welcome-message">
					<h2>Editar perfil</h2>
				</div>
				<!-- Edit Personal Info -->
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="widget personal-info">
							<h3 class="widget-header user">Editar Informacion Personal</h3>
							<form method="post">
								{% csrf_token %}
								<!-- First Name -->
								<div class="form-group">
									<label for="first-name">Nombre</label>
									{% render_field user_form.first_name class+="form-control" id="first-name" %}

								</div>
								<!-- Last Name -->
								<div class="form-group">
									<label for="last-name">Apellido</label>
									{% render_field user_form.last_name class+="form-control" id="last-name" %}
								</div>
								<div class="form-group">
									<label for="user-address">Direccion</label>
									{% render_field user_form.address class+="form-control" id="user-address" %}
								</div>
								<div class="form-group">
									<label for="user-phone">Telefono</label>
									{% render_field user_form.phone class+="form-control" id="user-phone" %}
								</div>
								<div class="form-group">
									<label for="user-email">Email</label>
									{% render_field user_form.email class+="form-control" id="user-email" %}
								</div>
								<!-- Submit button -->
								<button class="btn btn-transparent" name="update_profile">Guardar cambios</button>
							</form>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<!-- Change Password -->
					<div class="widget change-password">
						<h3 class="widget-header user">Cambiar Contraseña</h3>
						<form method="post">
							{% csrf_token %}
							<!-- Current Password -->
							<div class="form-group">
								<label for="current-password">Contraseña Actual</label>
								{% render_field password_form.old_password class+="form-control" id="current-password" %}
							</div>
							<!-- New Password -->
							<div class="form-group">
								<label for="new-password">Nueva Contraseña</label>
								{% render_field password_form.new_password1 class+="form-control" id="new-password" %}
							</div>
							<!-- Confirm New Password -->
							<div class="form-group">
								<label for="repeat-new-password">Confirmar Nueva Contraseña</label>
								{% render_field password_form.new_password2 class+="form-control" id="repeat-new-password" %}
							</div>
							<!-- Submit Button -->
							<button class="btn btn-transparent" name="change_password">Cambiar Contraseña</button>
						</form>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

rental_django/templates/register.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block title %}{{pagetitle}}{% endblock %}
{% block content %}
<section class="login py-5 border-top-1">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 align-item-center">
          <div class="border border">
            <h3 class="bg-gray p-4">Registro</h3>
            <form method="post">
                {% csrf_token %}
                <div class="row px-4 my-2">
                    <div class="col">
                      {{ form.f_name | add_class:"form-control" | attr:"placeholder:Nombre" | attr:"required" }}
                    </div>
                    <div class="col">
                        {{ form.l_name | add_class:"form-control" | attr:"placeholder:Apellido" | attr:"required" }}
                    </div>
                </div>
                <div class="row px-4 py-2">
                    <div class="col">
                        {{ form.username | add_class:"form-control" | attr:"placeholder:Nombre de Usuario" | attr:"required" }}
                    </div>
                    <div class="col">
                        {{ form.email | add_class:"form-control" | attr:"placeholder:Correo" | attr:"required" }}
                    </div>
                </div>
                <div class="row px-4 py-2">
                    <div class="col">
                        {{ form.rut | add_class:"form-control" | attr:"placeholder:RUT" | attr:"required" }}
                    </div>
                    <div class="col">
                        {{ form.phone | add_class:"form-control" | attr:"placeholder:Telefono" | attr:"required" }}
                    </div>
                </div>
                <div class="row px-4 py-2">
                    <div class="col">
                        {{ form.address | add_class:"form-control" | attr:"placeholder:Dirección" | attr:"required" }}
                    </div>
                </div>
                <div class="row px-4 py-2">
                    <div class="col">
                        {{ form.password | add_class:"form-control" | attr:"placeholder:Contraseña" | attr:"required" }}
                    </div>
                    <div class="col">
                        {{ form.password_repeat | add_class:"form-control" | attr:"placeholder:Repetir Contraseña" | attr:"required" }}
                    </div>
                </div>
              <fieldset class="p-4">
                <button type="submit" class="btn btn-primary font-weight-bold mt-3">Registrate Ahora</button>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}