rental_django/rental_django/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('property.urls', namespace='property')),
    path('', include('users.urls', namespace='users'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rental_django/users/urls.py
from django.urls import path
from .views import index_view, login_view, register_view, logout_view, dashboard_view, edit_profile_view

app_name = 'users'

urlpatterns = [
    path('', index_view, name='index'),
    path('entrar/', login_view, name='login'),
    path('registro/', register_view, name='register'),
    path('salir/', logout_view, name='logout'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('dashboard/editar/', edit_profile_view, name='edit_profile')
]

rental_django/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <!-- ** Basic Page Needs ** -->
  <meta charset="utf-8">
  <title>{% block title %}{% endblock title %} - RENTAL</title>
  <!-- ** Mobile Specific Metas ** -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Rental web page Talento Digital">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <!-- favicon -->
  <link href="{% static 'images/favicon.png' %}" rel="shortcut icon">
  <!-- 
  Essential stylesheets
  =====================================-->
  <link href="{% static 'plugins/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap/bootstrap-slider.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/slick/slick.css" rel="stylesheet' %}">
  <link href="{% static 'plugins/slick/slick-theme.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body class="body-wrapper">
{% include 'layouts/header.html'%}

{% block content %}{% endblock content %}

{% include 'layouts/footer.html'%}

<!-- 
Essential Scripts
=====================================-->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/bootstrap-slider.js' %}"></script>
<script src="{% static 'plugins/tether/js/tether.min.js' %}"></script>
<script src="{% static 'plugins/raty/jquery.raty-fa.js' %}"></script>
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<script src="{% static 'plugins/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

<script src="{% static 'js/script.js' %}"></script>
{% include 'layouts/messages.html' %}
</body>

</html>

rental_django/templates/layouts/footer.html
  <!-- Footer Bottom -->
  <footer class="footer-bottom">
    <!-- Container Start -->
    <div class="container">
      <div class="row">
        <div class="col-lg-6 text-center text-lg-left mb-3 mb-lg-0">
          <!-- Copyright -->
          <div class="copyright">
            <p>Copyright &copy; <script>
                var CurrentYear = new Date().getFullYear()
                document.write(CurrentYear)
              </script>Jose Duarte para Talento Digital</a></p>
          </div>
        </div>
        <div class="col-lg-6">
          <!-- Social Icons -->
          <ul class="social-media-icons text-center text-lg-right">
            <li><a class="fa fa-facebook" href="https://www.facebook.com/themefisher"></a></li>
            <li><a class="fa fa-twitter" href="https://www.twitter.com/themefisher"></a></li>
            <li><a class="fa fa-pinterest-p" href="https://www.pinterest.com/themefisher"></a></li>
            <li><a class="fa fa-github-alt" href="https://www.github.com/themefisher"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Container End -->
    <!-- To Top -->
    <div class="scroll-top-to">
      <i class="fa fa-angle-up"></i>
    </div>
  </footer>

rental_django/templates/layouts/header.html
{% load static %}
<header>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-expand-lg navbar-light navigation">
					<a class="navbar-brand" href="{% url 'users:index' %}">
						<img src="{% static 'images/logo.png' %}" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto main-nav ">
							<li class="nav-item active">
								<a class="nav-link" href="index.html">Home</a>
							</li>
							<li class="nav-item dropdown dropdown-slide @@dashboard">
								<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#!">Dashboard<span><i class="fa fa-angle-down"></i></span>
								</a>

								<!-- Dropdown list -->
								<ul class="dropdown-menu">
									<li><a class="dropdown-item @@dashboardPage" href="dashboard.html">Dashboard</a></li>
									<li><a class="dropdown-item @@dashboardMyAds" href="dashboard-my-ads.html">Dashboard My Ads</a></li>
									<li><a class="dropdown-item @@dashboardFavouriteAds" href="dashboard-favourite-ads.html">Dashboard Favourite Ads</a></li>
									<li><a class="dropdown-item @@dashboardArchivedAds" href="dashboard-archived-ads.html">Dashboard Archived Ads</a></li>
									<li><a class="dropdown-item @@dashboardPendingAds" href="dashboard-pending-ads.html">Dashboard Pending Ads</a></li>
									
									<li class="dropdown dropdown-submenu dropright">
										<a class="dropdown-item dropdown-toggle" href="#!" id="dropdown0501" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sub Menu</a>
					
										<ul class="dropdown-menu" aria-labelledby="dropdown0501">
											<li><a class="dropdown-item" href="index.html">Submenu 01</a></li>
											<li><a class="dropdown-item" href="index.html">Submenu 02</a></li>
										</ul>
									</li>
								</ul>
							</li>
							<li class="nav-item dropdown dropdown-slide @@pages">
								<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Pages <span><i class="fa fa-angle-down"></i></span>
								</a>
								<!-- Dropdown list -->
								<ul class="dropdown-menu">
									<li><a class="dropdown-item @@about" href="about-us.html">About Us</a></li>
									<li><a class="dropdown-item @@contact" href="contact-us.html">Contact Us</a></li>
									<li><a class="dropdown-item @@profile" href="user-profile.html">User Profile</a></li>
									<li><a class="dropdown-item @@404" href="404.html">404 Page</a></li>
									<li><a class="dropdown-item @@package" href="package.html">Package</a></li>
									<li><a class="dropdown-item @@singlePage" href="single.html">Single Page</a></li>
									<li><a class="dropdown-item @@store" href="store.html">Store Single</a></li>
									<li><a class="dropdown-item @@blog" href="blog.html">Blog</a></li>
									<li><a class="dropdown-item @@singleBlog" href="single-blog.html">Blog Details</a></li>
									<li><a class="dropdown-item @@terms" href="terms-condition.html">Terms &amp; Conditions</a></li>
								</ul>
							</li>
							<li class="nav-item dropdown dropdown-slide @@listing">
								<a class="nav-link dropdown-toggle" href="#!" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Listing <span><i class="fa fa-angle-down"></i></span>
								</a>
								<!-- Dropdown list -->
								<ul class="dropdown-menu">
									<li><a class="dropdown-item @@category" href="category.html">Ad-Gird View</a></li>
									<li><a class="dropdown-item @@listView" href="ad-list-view.html">Ad-List View</a></li>
									
									<li class="dropdown dropdown-submenu dropleft">
										<a class="dropdown-item dropdown-toggle" href="#!" id="dropdown0201" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sub Menu</a>
					
										<ul class="dropdown-menu" aria-labelledby="dropdown0201">
											<li><a class="dropdown-item" href="index.html">Submenu 01</a></li>
											<li><a class="dropdown-item" href="index.html">Submenu 02</a></li>
										</ul>
									</li>
								</ul>
							</li>
						{% if request.user.is_authenticated %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'users:logout' %}">Salir</a>
							</li>
						{% endif %}	
						</ul>
						<ul class="navbar-nav ml-auto mt-10">		
							<li class="nav-item">
							{% if request.user.is_authenticated %}
								<a class="nav-link login-button" href="{% url 'users:dashboard' %}">Mis Datos</a>
							{% else %}
								<a class="nav-link login-button" href="{% url 'users:login' %}">Iniciar Sesión</a>
							{% endif %}
							</li>
							<li class="nav-item">
								<a class="nav-link text-white add-button" href="{% url "users:register" %}"><i class="fa fa-plus-circle"></i> Agregar Aviso</a>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>

rental_django/templates/layouts/messages.html
{% if messages %}
<div class="fixed-top mt-3 container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
</div>
<script>
    setTimeout(function() {
        $(".alert").alert('close')
    }, 5000);
</script>
{% endif %}